# Generated by Django 2.2.4 on 2021-03-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210303_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severance',
            name='int_rate',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='severance',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='severance',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
