# Generated by Django 2.2.4 on 2021-03-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210304_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severance',
            name='int_rate',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
