# Generated by Django 2.2.4 on 2021-03-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210304_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='severance',
            name='relation_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='severance',
            name='days_complete_month',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='severance',
            name='days_month_worked',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='severance',
            name='int_rate',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='severance',
            name='seniority',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='severance',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
