# Generated by Django 2.2.4 on 2021-03-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210304_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='severance',
            old_name='seniority',
            new_name='comp_advance_notice',
        ),
    ]
