# Generated by Django 2.2.4 on 2021-03-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210305_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='severance',
            name='comp_seniority',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True),
        ),
    ]
